# Generated by Django 3.1.5 on 2023-04-14 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Transanctions', '0001_initial'),
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transanction',
            name='receiver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receiver_transanction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transanction',
            name='sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sender_transanction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transanction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transanction_wallet', to='Wallet.wallet'),
        ),
    ]
