# Generated by Django 3.1.5 on 2023-04-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transanctions', '0002_auto_20230414_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transanctionprofile',
            name='transanction_category',
            field=models.PositiveSmallIntegerField(choices=[(3, '> 1,000,000'), (0, '< 100,000'), (2, '< 1,000,000'), (1, '> 100,000'), (4, '> 1,000,000')], default=0),
        ),
        migrations.AlterField(
            model_name='transanctionprofile',
            name='transanction_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'AFRICA'), (1, 'KENYA'), (2, 'WORLD')], default=1),
        ),
    ]
